# 4. Stitch outputs together
- Once you have fitted the weak, medium and dense diads, stitch them all together, and apply the Ne correction model

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import DiadFit as pf
pf.__version__

'0.0.58'

In [2]:
import os
DayFolder=os.getcwd()
meta_path=DayFolder +  '\MetaData'
spectra_path=DayFolder + '\Spectra'

## Load in specra, and combine

In [3]:
import os.path
from os import path
if path.exists('Discarded_df.xlsx'):
    discard=pd.read_excel('Discarded_df.xlsx')
else:
    discard=None
if path.exists('Weak_Diads.xlsx'):
    grp1=pd.read_excel('Weak_Diads.xlsx')
else:
    grp1=None
if path.exists('Medium_Diads.xlsx'):
    grp2=pd.read_excel('Medium_Diads.xlsx')
else:
    grp2=None
if path.exists('Strong_Diads.xlsx'):
    grp3=pd.read_excel('Strong_Diads.xlsx')
else:
    grp3=None
if path.exists('Names_for_notes.xlsx'):
    notes=pd.read_excel('Names_for_notes.xlsx')
else:
    notes=None
df2=pd.concat([grp1, grp2, grp3], axis=0)
if discard is not None:
    discard_cols=discard[discard.columns.intersection(df2.columns)]
    df2=pd.concat([df2, discard_cols])

In [4]:
df2

,Unnamed: 0,filename,Splitting,Diad1_Combofit_Cent,Diad1_Combofit_Height,Diad1_Voigt_Cent,Diad1_Voigt_Area,Diad1_Voigt_Sigma,Diad1_Residual,Diad1_Prop_Lor,...,HB2_Sigma,C13_Cent,C13_Area,C13_Sigma,Diad2_Gauss_Cent,Diad2_Gauss_Area,Diad2_Gauss_Sigma,Diad1_Gauss_Cent,Diad1_Gauss_Area,Diad1_Gauss_Sigma
0,0,FDCA-P67-1_CRR_DiadFit,103.316817,1285.294984,628.365322,1285.294984,969.773020,0.592048,4.241360,0.570835,...,0.641608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,FDCA-P70-2,103.211232,1285.558151,677.113797,1285.558201,920.173337,0.528469,2.266037,0.534036,...,0.618413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,FDCA-P71-1,103.159955,1285.653145,779.342335,1285.653195,1000.432096,0.517164,3.350997,0.441538,...,0.605902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,FDCA-P71-2,103.181994,1285.647864,561.542145,1285.647864,719.155321,0.510665,3.692754,0.469622,...,0.578740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,FDCA-P72-1_CRR_DiadFit,103.153586,1285.737721,441.215080,1285.737721,534.500513,0.502610,3.220563,0.362720,...,0.545667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,0,FDCA-P8-2,105.226970,1281.208853,5252.652313,1281.208903,13963.088155,0.924072,5.704611,0.830558,...,2.688818,1369.129202,303.128597,0.448138,1387.758551,2746.159778,14.550485,1282.013273,1766.351572,13.606649
91,0,FDCA-P8-3,105.224047,1281.213655,5479.683995,1281.213705,14610.588141,0.929276,5.734635,0.825231,...,2.693863,1369.122586,320.159497,0.448978,1387.485677,2818.282006,14.590332,1281.635908,1962.492244,14.139892
92,0,FDCA-P9-1,105.183404,1281.285411,4742.816565,1281.285461,12515.816274,0.928378,5.132173,0.804832,...,2.670436,1369.129689,275.243092,0.445074,1386.864151,2590.963055,14.802361,1281.722387,1731.006797,13.817551
93,0,FDCA-P9-2,105.175045,1281.285049,4898.570506,1281.285099,13077.657169,0.940507,5.779881,0.803712,...,2.678749,1369.130909,282.144394,0.448021,1387.072761,2855.254942,14.601121,1281.870750,1907.494411,13.615911
94,0,FDCA-P9-3_CRR_DiadFit,105.175701,1281.284443,5362.179436,1281.284493,14264.865912,0.921000,5.484284,0.839572,...,2.642564,1369.138658,305.738216,0.446689,1386.949013,2892.207104,14.753173,1282.059357,1908.217036,14.539588

In [5]:
df2.to_clipboard(excel=True)

## First, get the metadata for this day

In [6]:
# Put the common string you can in all your Ne lines here
ID_str='_'
file_ext_meta='txt' # Will only take files of this type 
diad_meta=pf.get_files(path=meta_path,
file_ext='txt', exclude_str=['N', 'FG', 'Cap','window'],
 sort=True)
diad_meta

['FDCA-P1-1.txt',
 'FDCA-P1-2.txt',
 'FDCA-P1-3.txt',
 'FDCA-P10-1.txt',
 'FDCA-P10-2.txt',
 'FDCA-P10-3.txt',
 'FDCA-P11-1.txt',
 'FDCA-P12-1.txt',
 'FDCA-P13-1.txt',
 'FDCA-P14-1.txt',
 'FDCA-P14-2.txt',
 'FDCA-P14-3.txt',
 'FDCA-P15-1.txt',
 'FDCA-P16-1.txt',
 'FDCA-P17-1.txt',
 'FDCA-P18-1.txt',
 'FDCA-P18-2.txt',
 'FDCA-P19-1.txt',
 'FDCA-P19-2.txt',
 'FDCA-P19-3.txt',
 'FDCA-P2-1.txt',
 'FDCA-P2-2.txt',
 'FDCA-P2-3.txt',
 'FDCA-P20-1.txt',
 'FDCA-P21-1.txt',
 'FDCA-P22-1.txt',
 'FDCA-P23-1.txt',
 'FDCA-P23-2.txt',
 'FDCA-P23-3.txt',
 'FDCA-P24-1.txt',
 'FDCA-P25-1.txt',
 'FDCA-P26-1.txt',
 'FDCA-P26-2.txt',
 'FDCA-P27-1.txt',
 'FDCA-P27-2.txt',
 'FDCA-P27-3.txt',
 'FDCA-P28-1.txt',
 'FDCA-P29-1.txt',
 'FDCA-P3-1.txt',
 'FDCA-P3-2.txt',
 'FDCA-P3-3.txt',
 'FDCA-P30-1.txt',
 'FDCA-P31-1.txt',
 'FDCA-P31-2.txt',
 'FDCA-P31-3.txt',
 'FDCA-P32-1.txt',
 'FDCA-P33-1.txt',
 'FDCA-P34-1.txt',
 'FDCA-P35-1.txt',
 'FDCA-P35-2.txt',
 'FDCA-P35-3.txt',
 'FDCA-P36-1.txt',
 'FDCA-P36-2.txt',
 'FDCA-P36-3.txt',
 'FDCA-P37-1.txt',
 'FDCA-P38-1.txt',
 'FDCA-P39-1.txt',
 'FDCA-P39-2.txt',
 'FDCA-P39-3.txt',
 'FDCA-P4-1.txt',
 'FDCA-P4-2.txt',
 'FDCA-P4-3.txt',
 'FDCA-P40-1.txt',
 'FDCA-P40-2.txt',
 'FDCA-P42-1.txt',
 'FDCA-P43-1.txt',
 'FDCA-P43-2.txt',
 'FDCA-P43-3.txt',
 'FDCA-P44-1.txt',
 'FDCA-P45-1.txt',
 'FDCA-P46-1.txt',
 'FDCA-P47-1.txt',
 'FDCA-P48-1.txt',
 'FDCA-P48-2.txt',
 'FDCA-P48-3.txt',
 'FDCA-P49-1.txt',
 'FDCA-P5-1.txt',
 'FDCA-P5-2.txt',
 'FDCA-P5-3.txt',
 'FDCA-P50-1.txt',
 'FDCA-P51-1.txt',
 'FDCA-P52-1.txt',
 'FDCA-P52-2.txt',
 'FDCA-P52-3.txt',
 'FDCA-P53-1.txt',
 'FDCA-P54-1.txt',
 'FDCA-P55-1.txt',
 'FDCA-P56-1.txt',
 'FDCA-P56-2.txt',
 'FDCA-P56-3.txt',
 'FDCA-P57-2.txt',
 'FDCA-P58-1.txt',
 'FDCA-P59-1.txt',
 'FDCA-P6-1.txt',
 'FDCA-P6-2.txt',
 'FDCA-P6-3.txt',
 'FDCA-P60-1.txt',
 'FDCA-P60-2.txt',
 'FDCA-P60-3.txt',
 'FDCA-P61-1.txt',
 'FDCA-P61-2.txt',
 'FDCA-P61-3.txt',
 'FDCA-P62-1.txt',
 'FDCA-P62-2.txt',
 'FDCA-P62-3.txt',
 'FDCA-P63-1.txt',
 'FDCA-P63-2.txt',
 'FDCA-P63-3.txt',
 'FDCA-P64-1.txt',
 'FDCA-P64-2.txt',
 'FDCA-P64-3.txt',
 'FDCA-P65-1.txt',
 'FDCA-P65-2.txt',
 'FDCA-P65-3.txt',
 'FDCA-P66-1.txt',
 'FDCA-P66-2.txt',
 'FDCA-P66-3.txt',
 'FDCA-P67-1.txt',
 'FDCA-P67-2.txt',
 'FDCA-P67-3.txt',
 'FDCA-P68-1.txt',
 'FDCA-P68-2.txt',
 'FDCA-P68-3.txt',
 'FDCA-P69-1.txt',
 'FDCA-P69-2.txt',
 'FDCA-P69-3.txt',
 'FDCA-P7-1.txt',
 'FDCA-P7-2.txt',
 'FDCA-P7-3.txt',
 'FDCA-P70-1.txt',
 'FDCA-P70-2.txt',
 'FDCA-P70-3.txt',
 'FDCA-P71-1.txt',
 'FDCA-P71-2.txt',
 'FDCA-P71-3.txt',
 'FDCA-P72-1.txt',
 'FDCA-P72-2.txt',
 'FDCA-P72-3.txt',
 'FDCA-P73-1.txt',
 'FDCA-P73-2.txt',
 'FDCA-P73-3.txt',
 'FDCA-P74-1.txt',
 'FDCA-P74-2.txt',
 'FDCA-P74-3.txt',
 'FDCA-P75-1.txt',
 'FDCA-P75-2.txt',
 'FDCA-P75-3.txt',
 'FDCA-P76-1.txt',
 'FDCA-P76-2.txt',
 'FDCA-P76-3.txt',
 'FDCA-P8-1.txt',
 'FDCA-P8-2.txt',
 'FDCA-P8-3.txt',
 'FDCA-P9-1.txt',
 'FDCA-P9-2.txt',
 'FDCA-P9-3.txt']

## Now get all the important information out of the metadata files

In [8]:
meta=pf.stitch_metadata_in_loop_witec(path=meta_path, 
Allfiles=diad_meta, prefix=False                          ,
trupower=False)
meta['filename'].iloc[0]

100%|████████████████████████████████████████████████████████████████████████████████| 156/156 [00:05<00:00, 26.63it/s]

Done
Oof, try not to work after midnight!

'FDCA-P45-1.txt'

In [9]:
meta

,filename,date,Month,Day,power (mW),Int_time (s),accumulations,Mag (X),duration,24hr_time,sec since midnight,Spectral Center
69,FDCA-P45-1.txt,"April 11, 2023\n",April,11.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",12:03:29 AM\n,86609.0,1325.004
70,FDCA-P46-1.txt,"April 11, 2023\n",April,11.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",12:16:32 AM\n,87392.0,1325.004
71,FDCA-P47-1.txt,"April 11, 2023\n",April,11.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",12:23:11 AM\n,87791.0,1325.004
72,FDCA-P48-1.txt,"April 11, 2023\n",April,11.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",12:31:37 AM\n,88297.0,1325.004
73,FDCA-P48-2.txt,"April 11, 2023\n",April,11.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",12:33:56 AM\n,88436.0,1325.004
...,...,...,...,...,...,...,...,...,...,...,...,...
64,FDCA-P42-1.txt,"April 10, 2023\n",April,10.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",11:15:27 PM\n,83727.0,1325.004
65,FDCA-P43-1.txt,"April 10, 2023\n",April,10.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",11:37:06 PM\n,85026.0,1325.004
66,FDCA-P43-2.txt,"April 10, 2023\n",April,10.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",11:41:51 PM\n,85311.0,1325.004
67,FDCA-P43-3.txt,"April 10, 2023\n",April,10.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",11:43:48 PM\n,85428.0,1325.004
68,FDCA-P44-1.txt,"April 10, 2023\n",April,10.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",11:55:18 PM\n,86118.0,1325.004

## Then get a simple file name you can stitch with the spectra

In [10]:
file_m=pf.extracting_filenames_generic(names=meta['filename'],
    prefix=False, str_prefix=" ",
   file_type='.txt')
# Checks they are all unique
file_m[0]

good job, no duplicate file names

'FDCA-P45-1'

## If you have notes you have written for each spectra, load them now

In [12]:
has_notes=True
if has_notes is True:
    notes=pd.read_excel('Names_for_notes.xlsx', sheet_name='Sheet1')
    file_notes=pf.extracting_filenames_generic(names=notes['Spectral Name'],
    prefix=False, str_prefix=" ", file_type='.txt')
    notes['name_for_matching']=file_notes

good job, no duplicate file names

## Now get filename from spectra into same form as metadata

In [14]:
# Remove these to get the pure file name
file_s=pf.extracting_filenames_generic(
    prefix=False, str_prefix=" ",
    names=df2['filename'].reset_index(drop=True),
   file_type='.txt')

# Remove the cosmic rays, as doesnt have it in the metatdata
file_s = np.char.replace(file_s.astype(str), "_CRR_DiadFit", "")

good job, no duplicate file names

In [15]:
file_s

array(['FDCA-P67-1', 'FDCA-P70-2', 'FDCA-P71-1', 'FDCA-P71-2',
       'FDCA-P72-1', 'FDCA-P72-2', 'FDCA-P72-3', 'FDCA-P74-2',
       'FDCA-P74-3', 'FDCA-P75-1', 'FDCA-P75-2', 'FDCA-P75-3',
       'FDCA-P76-1', 'FDCA-P76-2', 'FDCA-P76-3', 'FDCA-P25-1',
       'FDCA-P26-1', 'FDCA-P27-2', 'FDCA-P28-1', 'FDCA-P30-1',
       'FDCA-P36-1', 'FDCA-P54-1', 'FDCA-P56-1', 'FDCA-P56-2',
       'FDCA-P56-3', 'FDCA-P57-2', 'FDCA-P58-1', 'FDCA-P59-1',
       'FDCA-P60-1', 'FDCA-P60-2', 'FDCA-P61-1', 'FDCA-P61-2',
       'FDCA-P61-3', 'FDCA-P62-2', 'FDCA-P62-3', 'FDCA-P63-1',
       'FDCA-P63-2', 'FDCA-P63-3', 'FDCA-P64-1', 'FDCA-P64-2',
       'FDCA-P64-3', 'FDCA-P65-1', 'FDCA-P65-2', 'FDCA-P65-3',
       'FDCA-P66-1', 'FDCA-P66-2', 'FDCA-P66-3', 'FDCA-P67-2',
       'FDCA-P67-3', 'FDCA-P68-1', 'FDCA-P68-2', 'FDCA-P68-3',
       'FDCA-P69-1', 'FDCA-P69-2', 'FDCA-P69-3', 'FDCA-P70-1',
       'FDCA-P70-3', 'FDCA-P73-1', 'FDCA-P73-2', 'FDCA-P73-3',
       'FDCA-P74-1', 'FDCA-P1-1', 'FDCA-P1-2', 'FDCA-P1-3', 'FDCA-P10-1',
       'FDCA-P10-2', 'FDCA-P10-3', 'FDCA-P11-1', 'FDCA-P12-1',
       'FDCA-P13-1', 'FDCA-P14-1', 'FDCA-P14-2', 'FDCA-P14-3',
       'FDCA-P15-1', 'FDCA-P16-1', 'FDCA-P17-1', 'FDCA-P18-1',
       'FDCA-P18-2', 'FDCA-P19-1', 'FDCA-P19-2', 'FDCA-P19-3',
       'FDCA-P2-1', 'FDCA-P2-2', 'FDCA-P2-3', 'FDCA-P20-1', 'FDCA-P21-1',
       'FDCA-P22-1', 'FDCA-P23-1', 'FDCA-P23-2', 'FDCA-P23-3',
       'FDCA-P24-1', 'FDCA-P26-2', 'FDCA-P27-1', 'FDCA-P27-3',
       'FDCA-P29-1', 'FDCA-P3-1', 'FDCA-P3-2', 'FDCA-P3-3', 'FDCA-P31-1',
       'FDCA-P31-2', 'FDCA-P31-3', 'FDCA-P32-1', 'FDCA-P33-1',
       'FDCA-P34-1', 'FDCA-P35-1', 'FDCA-P35-2', 'FDCA-P35-3',
       'FDCA-P36-2', 'FDCA-P36-3', 'FDCA-P37-1', 'FDCA-P38-1',
       'FDCA-P39-1', 'FDCA-P39-2', 'FDCA-P39-3', 'FDCA-P4-1', 'FDCA-P4-2',
       'FDCA-P4-3', 'FDCA-P40-1', 'FDCA-P40-2', 'FDCA-P42-1',
       'FDCA-P43-1', 'FDCA-P43-2', 'FDCA-P43-3', 'FDCA-P44-1',
       'FDCA-P45-1', 'FDCA-P46-1', 'FDCA-P47-1', 'FDCA-P48-1',
       'FDCA-P48-2', 'FDCA-P48-3', 'FDCA-P49-1', 'FDCA-P5-1', 'FDCA-P5-2',
       'FDCA-P5-3', 'FDCA-P50-1', 'FDCA-P51-1', 'FDCA-P52-1',
       'FDCA-P52-2', 'FDCA-P52-3', 'FDCA-P53-1', 'FDCA-P55-1',
       'FDCA-P6-1', 'FDCA-P6-2', 'FDCA-P6-3', 'FDCA-P60-3', 'FDCA-P62-1',
       'FDCA-P7-1', 'FDCA-P7-2', 'FDCA-P7-3', 'FDCA-P71-3', 'FDCA-P8-1',
       'FDCA-P8-2', 'FDCA-P8-3', 'FDCA-P9-1', 'FDCA-P9-2', 'FDCA-P9-3'],
      dtype='<U10')

In [16]:
# Combining them together
meta['name_for_matching']=file_m
df2['name_for_matching']=file_s
df2['Name_for_Secondary_Phases']=file_s
df_combo=pd.merge(df2, meta, on='name_for_matching', how='left')

if has_notes is True:
    print('yes')
    df_combo=pd.merge(notes, df_combo, on='name_for_matching', how='right')
    df_sorted = df_combo.sort_values(by=['To use', 'sec since midnight'], ascending=[False, True])
else:
    df_sorted=df_combo.sort_values(by=['sec since midnight'], ascending=[True])

yes

In [21]:
df_sorted['sec since midnight']

61     52962.0
62     53247.0
63     53765.0
81     54077.0
82     54384.0
        ...
10    108424.0
11    108660.0
12    109955.0
13    110235.0
14    110431.0
Name: sec since midnight, Length: 156, dtype: float64

In [22]:
from pickle import load
import pickle
import os
pickle_path=os.getcwd()
file_pkl=pickle_path + '/' + 'Ne_Line_Regression_Example_cali.pck'
with open(file_pkl, 'rb') as file_handle:
    my_loaded_model = pickle.load(file_handle)

In [23]:
df_sorted['Ne_Correction']=my_loaded_model(df_sorted['sec since midnight'])
df_sorted.insert(1,'Corrected_Splitting', df_sorted['Ne_Correction']*df_sorted['Splitting'])

ValueError: cannot insert Corrected_Splitting, already exists

In [19]:
df_sorted.to_excel('FI_fitting.xlsx')

In [25]:
df_sorted.to_clipboard(excel=True)

## If you have secondary phases, now is the time to merge those in

In [17]:
if path.exists('Carb_Peak_fits.xlsx'):
    Carb=pd.read_excel('Carb_Peak_fits.xlsx')
else:
    Carb=None
if path.exists('SO2_Peak_fits.xlsx'):
    SO2=pd.read_excel('SO2_Peak_fits.xlsx')
else:
    SO2=None
if SO2 is not None and Carb is not None:
    Sec_Phases=pd.merge(SO2, Carb, on='filename', how='outer')
elif SO2 is not None and Carb is None:
    Sec_Phases=SO2
elif SO2 is None and Carb is not None:
    Sec_Phases=Carb
else:
    Sec_Phases=None
Sec_Phases

In [18]:
# Remove these to get the pure file name
if Sec_Phases is not None:
    file_sec_phase=pf.extracting_filenames_generic(
        prefix=True, str_prefix=" ",
        names=Sec_Phases['filename'].reset_index(drop=True),
       file_type='.txt')

    file_sec_phase

In [19]:
df_combo['name_for_matching']=df_combo['Name_for_Secondary_Phases']

if Sec_Phases is not None:
    Sec_Phases['name_for_matching']=file_sec_phase
    df_combo_sec_phase=pd.merge(df_sorted, Sec_Phases, 
    on='name_for_matching', how='outer')
    
else:
    df_combo_sec_phase=df_sorted
    df_combo_sec_phase['To use']=np.nan

### Add some more useful columns

In [20]:
if 'Peak_Area_Carb' in df_combo_sec_phase.columns:
    df_combo_sec_phase['Carb_Diad_Ratio']=(df_combo_sec_phase['Peak_Area_Carb']/(df_combo_sec_phase['Diad1_Voigt_Area']
                      +df_combo_sec_phase['Diad2_Voigt_Area']))
else:
    df_combo_sec_phase['Carb_Diad_Ratio']=0
    
if 'Peak_Area_SO2' in df_combo_sec_phase.columns:
    df_combo_sec_phase['SO2_Diad_Ratio']=(df_combo_sec_phase['Peak_Area_SO2']/(df_combo_sec_phase['Diad1_Voigt_Area']
                      +df_combo_sec_phase['Diad2_Voigt_Area']))
    
else:
    df_combo_sec_phase['SO2_Diad_Ratio']=0

## Lets re-arrange columns for most useful outputs

In [21]:
cols_to_move=['date', 'filename_x',  'To use', 'Diad1_Fit', 'Corrected_Splitting', 'Splitting', 'SO2_Diad_Ratio', 'Carb_Diad_Ratio']
df_combo_sec_phase.to_excel('FI_fitting_w_sec_phases.xlsx')

In [22]:
df_combo_sec_phase = df_combo_sec_phase[cols_to_move + [col for col in df_combo_sec_phase.columns if col not in cols_to_move]]

In [23]:
df_combo_sec_phase.to_clipboard(excel=True)

In [24]:
df_combo_sec_phase

,date,filename_x,To use,Diad1_Fit,Corrected_Splitting,Splitting,SO2_Diad_Ratio,Carb_Diad_Ratio,Spectral Name,Diad2_Fit,...,Day,power (mW),Int_time (s),accumulations,Mag (X),duration,24hr_time,sec since midnight,Spectral Center,Ne_Correction
9,"April 12, 2023\n",02 35C_aq1,NaN,NaN,104.185249,104.425646,0,0,02 35C_aq1.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",9:28:04 AM\n,34084.0,1325.004,0.997698
10,"April 12, 2023\n",05 35C_aq2,NaN,NaN,104.058447,104.297974,0,0,05 35C_aq2.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",9:46:02 AM\n,35162.0,1325.004,0.997703
11,"April 12, 2023\n",07 35C_aq3,NaN,NaN,103.759066,103.997925,0,0,07 35C_aq3.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",9:58:38 AM\n,35918.0,1325.004,0.997703
12,"April 12, 2023\n",09 35C_aq4,NaN,NaN,103.659216,103.899715,0,0,09 35C_aq4.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",10:19:51 AM\n,37191.0,1325.004,0.997685
13,"April 12, 2023\n",11 35C_aq5,NaN,NaN,103.534092,103.776154,0,0,11 35C_aq5.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",11:00:51 AM\n,39651.0,1325.004,0.997667
14,"April 12, 2023\n",13 35C_aq6,NaN,NaN,103.439589,103.684889,0,0,13 35C_aq6.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",11:24:26 AM\n,41066.0,1325.004,0.997634
4,"April 12, 2023\n",15 35C_aq7,NaN,NaN,103.249351,103.494632,0,0,15 35C_aq7.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",11:43:05 AM\n,42185.0,1325.004,0.997630
15,"April 12, 2023\n",17 35C_aq8,NaN,NaN,103.110759,103.355196,0,0,17 35C_aq8.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '31s']",12:03:16 PM\n,43396.0,1325.004,0.997635
5,"April 12, 2023\n",19 35C_aq9,NaN,NaN,102.931282,103.176010,0,0,19 35C_aq9.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",12:13:38 PM\n,44018.0,1325.004,0.997628
0,"April 12, 2023\n",21 35C_aq10,NaN,NaN,102.769706,103.014645,0,0,21 35C_aq10.txt,NaN,...,12.0,NaN,45.0,5.0,5.0,"['0h', '3m', '46s']",12:23:25 PM\n,44605.0,1325.004,0.997622
1,"April 12, 2023\n",23 377C_aq11,NaN,NaN,102.769383,103.016865,0,0,23 377C_aq11.txt,NaN,...,12.0,NaN,45.0,5.0,5.0,"['0h', '3m', '46s']",1:10:43 PM\n,47443.0,1325.004,0.997598
6,"April 12, 2023\n",26 377C_aq12,NaN,NaN,102.938574,103.188088,0,0,26 377C_aq12.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",1:31:07 PM\n,48667.0,1325.004,0.997582
7,"April 12, 2023\n",28 377C_aq13,NaN,NaN,103.101246,103.351834,0,0,28 377C_aq13.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",1:41:27 PM\n,49287.0,1325.004,0.997575
16,"April 12, 2023\n",30 377C_aq14,NaN,NaN,103.260272,103.511594,0,0,30 377C_aq14.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",2:02:16 PM\n,50536.0,1325.004,0.997572
17,"April 12, 2023\n",32 377C_aq15,NaN,NaN,103.413184,103.665223,0,0,32 377C_aq15.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",2:11:57 PM\n,51117.0,1325.004,0.997569
18,"April 12, 2023\n",34 377C_aq16,NaN,NaN,103.551688,103.806208,0,0,34 377C_aq16.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '31s']",2:27:56 PM\n,52076.0,1325.004,0.997548
19,"April 12, 2023\n",36 377C_aq17,NaN,NaN,103.645949,103.900322,0,0,36 377C_aq17.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",2:34:56 PM\n,52496.0,1325.004,0.997552
20,"April 12, 2023\n",38 377C_aq18,NaN,NaN,103.800662,104.055130,0,0,38 377C_aq18.txt,NaN,...,12.0,NaN,30.0,5.0,5.0,"['0h', '2m', '32s']",2:43:07 PM\n,52987.0,1325.004,0.997554
21,"April 12, 2023\n",40 377C_aq19,NaN,NaN,103.982649,104.238458,0,0,40 377C_aq19.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",2:51:47 PM\n,53507.0,1325.004,0.997546
22,"April 12, 2023\n",42 377C_aq20,NaN,NaN,104.132387,104.389262,0,0,42 377C_aq20.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",2:58:08 PM\n,53888.0,1325.004,0.997539
23,"April 12, 2023\n",44 377C_rep1,NaN,NaN,104.121069,104.379535,0,0,44 377C_rep1.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",3:09:19 PM\n,54559.0,1325.004,0.997524
2,"April 12, 2023\n",46 377C_rep2,NaN,NaN,104.125686,104.385155,0,0,46 377C_rep2.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",3:27:50 PM\n,55670.0,1325.004,0.997514
3,"April 12, 2023\n",48 377C_rep2b,NaN,NaN,104.107235,104.366758,0,0,48 377C_rep2b.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '41s']",3:38:51 PM\n,56331.0,1325.004,0.997513
8,"April 12, 2023\n",50 377C_rep3,NaN,NaN,104.107095,104.366061,0,0,50 377C_rep3.txt,NaN,...,12.0,NaN,20.0,5.0,5.0,"['0h', '1m', '42s']",3:52:45 PM\n,57165.0,1325.004,0.997519