In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import DiadFit as pf

## Add folder here
- if you are on a mac, you might have to change the file path slightly, I think you use slashes the other way maybe?

In [2]:
path=r'G:\My Drive\Postdoc\MeltInclusion_SampleStuff\Raman\Day20\Metadata'
All_files=pf.get_all_txt_files(path)
#All_files

## These are the functions doing the work. Just run this cell!

In [3]:
df_stitch=pf.stitch_in_loop(Allfiles=All_files, path=path, prefix=False)
df_stitch.to_excel(path+'/'+ 'times.xlsx')
df_stitch

working on file01 MS14_5_Zscan.txt
working on file02 MS14_5_H2O.txt
working on file03 MS14_5_Ol.txt
working on file04 BL2_MI1_Zscan_highback.txt
working on file05 MS14_12_MI1_zscan.txt
working on file06 MS14_12_MI1_H2O.txt
working on file07 MS14_12_MI1_Ol.txt
working on file08 SC3_2_MI2_Zscan.txt
working on file09 20X_NS9_MI3.txt
working on file10 50X_NS9_MI3.txt
working on file11 NS9_MI3_2300wavenumber.txt
working on file12 Ne_Lines_1.txt
working on file13 NS9_MI3_8mW.txt
working on file14 NS9_MI3_12mW.txt
working on file15 Ne_Lines_2.txt
working on file16 CC13_MI10_20X.txt
working on file17 CC13_MI10_50X.txt
working on file18 Ne_Lines_3.txt
working on file19 CC13_MI10_50X_12mW.txt
working on file20 CC13_MI10_50X_8mW.txt
working on file21 Ne_Lines_4.txt
working on file22 CC13_MI11_20X.txt
working on file23 CC13_MI11_50X.txt
working on file24 CC13_MI11_12mW.txt
working on file25 CC13_MI12_20X.txt
working on file26 CC13_MI12_20X.txt
working on file27 CC13_MI12_12mW.txt
working on file28 Ne_Lines_5.txt
working on file29 CC13_MI13_20X.txt
working on file30 CC13_MI13.txt
working on file31 CC13_MI13_50X.txt
working on file32 CC13_MI14_20X.txt
working on file33 CC13_MI14_12mW.txt
working on file34 Ne_Lines_6.txt
working on file35 CC2_5X.txt
working on file36 CC2_MI10_20X.txt
working on file37 CC2_MI10_50X.txt
working on file38 CC2_MI10_12mW.txt
working on file39 CC2_MI11_50X.txt
working on file40 CC2_MI11.txt
working on file41 Ne_Lines_7.txt
working on file42 CC2_MI12_50X.txt
working on file43 CC2_MI12.txt
working on file44 CC2_MI13.txt
working on file45 CC2_MI13.txt
working on file46 CC2_MI14_20X.txt
working on file47 CC2_MI14.txt
working on file48 Ne_Lines_8.txt
Done

g:\my drive\berkeley_new\diadfit_outer\src\DiadFit\importing_data_files.py:552: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Time_Df_2['index']=Time_Df_2.index

,filename,date,power (mW),Int_time (s),accumulations,Mag (X),duration,24hr_time,sec since midnight,index
0,01 MS14_5_Zscan.txt,"April 13, 2022\n",9.974,3.0,10.0,100.0,"['0h', '0m', '41s']",10:14:15 AM\n,36855.0,0
1,02 MS14_5_H2O.txt,"April 13, 2022\n",9.983,30.0,10.0,100.0,"['0h', '5m', '3s']",10:17:13 AM\n,37033.0,1
2,03 MS14_5_Ol.txt,"April 13, 2022\n",9.979,2.0,10.0,100.0,"['0h', '0m', '23s']",10:24:05 AM\n,37445.0,2
3,04 BL2_MI1_Zscan_highback.txt,"April 13, 2022\n",9.963,4.0,10.0,50.0,"['0h', '0m', '50s']",10:29:48 AM\n,37788.0,3
4,05 MS14_12_MI1_zscan.txt,"April 13, 2022\n",9.934,4.0,10.0,50.0,"['0h', '0m', '49s']",10:35:34 AM\n,38134.0,4
5,06 MS14_12_MI1_H2O.txt,"April 13, 2022\n",9.940,30.0,10.0,50.0,"['0h', '5m', '3s']",10:38:24 AM\n,38304.0,5
6,07 MS14_12_MI1_Ol.txt,"April 13, 2022\n",9.942,2.0,10.0,50.0,"['0h', '0m', '23s']",10:44:24 AM\n,38664.0,6
7,08 SC3_2_MI2_Zscan.txt,"April 13, 2022\n",9.950,3.0,10.0,50.0,"['0h', '0m', '40s']",10:48:32 AM\n,38912.0,7
10,11 NS9_MI3_2300wavenumber.txt,"April 13, 2022\n",10.057,45.0,3.0,50.0,"['0h', '2m', '17s']",12:16:26 PM\n,44186.0,10
11,12 Ne_Lines_1.txt,"April 13, 2022\n",10.064,45.0,3.0,50.0,"['0h', '2m', '17s']",12:22:42 PM\n,44562.0,11
12,13 NS9_MI3_8mW.txt,"April 13, 2022\n",8.052,45.0,5.0,50.0,"['0h', '3m', '47s']",12:25:57 PM\n,44757.0,12
13,14 NS9_MI3_12mW.txt,"April 13, 2022\n",11.979,45.0,4.0,50.0,"['0h', '3m', '40s']",12:31:19 PM\n,45079.0,13
14,15 Ne_Lines_2.txt,"April 13, 2022\n",11.988,45.0,3.0,50.0,"['0h', '2m', '17s']",12:36:06 PM\n,45366.0,14
17,18 Ne_Lines_3.txt,"April 13, 2022\n",12.114,45.0,3.0,50.0,"['0h', '2m', '17s']",1:47:15 PM\n,49635.0,17
18,19 CC13_MI10_50X_12mW.txt,"April 13, 2022\n",12.114,45.0,5.0,50.0,"['0h', '3m', '47s']",1:51:07 PM\n,49867.0,18
19,20 CC13_MI10_50X_8mW.txt,"April 13, 2022\n",8.008,45.0,5.0,50.0,"['0h', '3m', '47s']",1:57:40 PM\n,50260.0,19
20,21 Ne_Lines_4.txt,"April 13, 2022\n",8.017,45.0,3.0,50.0,"['0h', '2m', '17s']",2:02:12 PM\n,50532.0,20
23,24 CC13_MI11_12mW.txt,"April 13, 2022\n",11.939,45.0,5.0,50.0,"['0h', '3m', '47s']",2:08:31 PM\n,50911.0,23
26,27 CC13_MI12_12mW.txt,"April 13, 2022\n",11.937,45.0,5.0,50.0,"['0h', '3m', '47s']",2:15:36 PM\n,51336.0,26
27,28 Ne_Lines_5.txt,"April 13, 2022\n",11.945,45.0,3.0,20.0,"['0h', '2m', '17s']",2:22:07 PM\n,51727.0,27
29,30 CC13_MI13.txt,"April 13, 2022\n",11.946,45.0,5.0,50.0,"['0h', '3m', '47s']",2:26:01 PM\n,51961.0,29
32,33 CC13_MI14_12mW.txt,"April 13, 2022\n",11.953,45.0,5.0,50.0,"['0h', '3m', '47s']",2:33:48 PM\n,52428.0,32
33,34 Ne_Lines_6.txt,"April 13, 2022\n",11.947,45.0,3.0,5.0,"['0h', '2m', '16s']",2:38:57 PM\n,52737.0,33
37,38 CC2_MI10_12mW.txt,"April 13, 2022\n",11.952,45.0,5.0,50.0,"['0h', '3m', '47s']",2:51:40 PM\n,53500.0,37
39,40 CC2_MI11.txt,"April 13, 2022\n",11.954,45.0,5.0,50.0,"['0h', '3m', '47s']",2:56:44 PM\n,53804.0,39
40,41 Ne_Lines_7.txt,"April 13, 2022\n",11.950,45.0,3.0,50.0,"['0h', '2m', '17s']",3:01:35 PM\n,54095.0,40
42,43 CC2_MI12.txt,"April 13, 2022\n",11.954,45.0,5.0,50.0,"['0h', '3m', '47s']",3:06:50 PM\n,54410.0,42
44,45 CC2_MI13.txt,"April 13, 2022\n",11.959,45.0,5.0,50.0,"['0h', '3m', '47s']",3:14:56 PM\n,54896.0,44
46,47 CC2_MI14.txt,"April 13, 2022\n",11.959,45.0,5.0,50.0,"['0h', '3m', '47s']",3:28:43 PM\n,55723.0,46
47,48 Ne_Lines_8.txt,"April 13, 2022\n",11.956,45.0,3.0,50.0,"['0h', '2m', '17s']",3:34:16 PM\n,56056.0,47